module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Quests', [{
      quest: 'Сакура национальный цветок в Японии?',
      answer: 'да',
      price: '100',
      theme_id: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      quest: 'Красный кенгуру национальное животное Австралии?',
      answer: 'да',
      price: '100',
      theme_id: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      quest: 'Олово обозначается в таблице Мендеелева как Sn?',
      answer: 'да',
      price: '100',
      theme_id: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      quest: 'Крона национальная валюта в Швеции?',
      answer: 'нет',
      price: '200',
      theme_id: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      quest: '128 элементов в переодической таблице Менделеева?',
      answer: 'нет',
      price: '200',
      theme_id: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      quest: 'На логотипе Porsche изображен осел?',
      answer: 'нет',
      price: '200',
      theme_id: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      quest: 'У марса два спутника?',
      answer: 'да',
      price: '400',
      theme_id: 3,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      quest: 'В России 11 часовых поясов?',
      answer: 'да',
      price: '400',
      theme_id: 3,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      quest: 'Нил самая длинная река в мире?',
      answer: 'да',
      price: '400',
      theme_id: 3,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      quest: 'У Золушки было 3 сводных сестры?',
      answer: 'нет',
      price: '500',
      theme_id: 4,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      quest: 'У Ивана Грозного было 7 жен',
      answer: 'да',
      price: '500',
      theme_id: 4,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      quest: 'На хоккейной площадке 9 мест для вбрасывания шайбы?',
      answer: 'да',
      price: '500',
      theme_id: 4,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    ], {});
  },
  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Quests', null, {});
  },
};
